### ISSUE TITLE
Code for GMM-Det and the dataset methodology is available at .

### ISSUE THREAD

**Issue by MartinaProgrammer** [dimitymiller/openset_detection#1]
Hi, I would like to know when the code and data set of GMM-DET will be open source. Looking forward to your reply!

**Comment by dimitymiller** [comment]
Hi @MartinaProgrammer, the Faster R-CNN experiments and dataset setup should be available by this week or next, with the RetinaNet experiments to follow shortly after.

**Comment by dimitymiller** [comment]
Faster R-CNN evaluate and dataset setup is available now, please refer to README of this repo to see the list of code to come and an ETA.
