### ISSUE TITLE
Positive GMM Uncertainties

### ISSUE THREAD

**Issue by z00kiii** [dimitymiller/openset_detection#7]
Hi, 
when using your approach i found that our GMM gives me negative (up to -1000) as well as positive (up to 60) uncertainties. As the log likelihood is used, i wonder if there shouldn’t be only negative values? Did you face something like this during your experiments or know a reason for it?

**Comment by dimitymiller** [comment]
Hi z00kii,

That sounds correct from what I found in my experiments and is reasonable for a GMM; given that the GMM is a continuous probability distribution with a probability density function, it can produce likelihoods that are greater than 1. This would give a positive log likelihood.
